"""Structure change

Revision ID: bd1b5f1bc8ff
Revises: 479eda2980c2
Create Date: 2019-08-05 09:27:15.358485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd1b5f1bc8ff'
down_revision = '479eda2980c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vote', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pitches_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pitches_id'], ['pitches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('comments', sa.Column('opinion', sa.String(length=255), nullable=True))
    op.add_column('comments', sa.Column('pitches_id', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('time_posted', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'comments', 'pitches', ['pitches_id'], ['id'])
    op.drop_column('comments', 'comment')
    op.drop_column('comments', 'title')
    op.add_column('pitches', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('pitches', sa.Column('content', sa.String(), nullable=True))
    op.create_foreign_key(None, 'pitches', 'categories', ['category_id'], ['id'])
    op.drop_column('pitches', 'upvotes')
    op.drop_column('pitches', 'body')
    op.drop_column('pitches', 'author')
    op.drop_column('pitches', 'downvotes')
    op.drop_column('pitches', 'category')
    op.drop_column('pitches', 'title')
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    op.drop_index('ix_users_username', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'pass_secure')
    op.drop_column('users', 'bio')
    op.add_column('pitches', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('downvotes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('body', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('upvotes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.drop_column('pitches', 'content')
    op.drop_column('pitches', 'category_id')
    op.add_column('comments', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'time_posted')
    op.drop_column('comments', 'pitches_id')
    op.drop_column('comments', 'opinion')
    op.drop_table('votes')
    op.drop_table('categories')
    # ### end Alembic commands ###
